<a href="https://colab.research.google.com/github/Carvas91/PyTroch/blob/main/dropout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [6]:
prob = .5

drop = nn.Dropout(p=prob)
x = torch.ones(10)

y = drop(x)

print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([0., 2., 2., 0., 2., 0., 2., 0., 2., 2.])
tensor(1.2000)


In [8]:
drop.eval()

y = drop(x)

print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)
