<a href="https://colab.research.google.com/github/Carvas91/PyTroch/blob/main/dropout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [9]:
prob = .5

drop = nn.Dropout(p=prob)
x = torch.ones(10)

y = drop(x)

print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 0., 2., 0., 2., 2., 2., 2., 0., 0.])
tensor(1.2000)


In [3]:
drop.eval()

y = drop(x)

print(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [10]:
drop.eval()

y = F.dropout(x)

print(y)
print(torch.mean(y))


tensor([0., 2., 0., 2., 0., 0., 0., 2., 2., 0.])
tensor(0.8000)


In [11]:
y = F.dropout(x, training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [12]:
drop.train()

y = drop(x)
print(y)

drop.eval()
y = drop(x)
print(y)



tensor([2., 0., 0., 0., 0., 2., 0., 0., 0., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
