<a href="https://colab.research.google.com/github/Carvas91/PyTroch/blob/main/train_dev_test_set.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
fakedata = np.tile(np.array([1,2,3,4]),(10,1)) + np.tile(10 * np.arange(1,11),(4,1)).T

fakelabels = np.arange(10) > 4

print(fakedata), print('')
print(fakelabels)

[[ 11  12  13  14]
 [ 21  22  23  24]
 [ 31  32  33  34]
 [ 41  42  43  44]
 [ 51  52  53  54]
 [ 61  62  63  64]
 [ 71  72  73  74]
 [ 81  82  83  84]
 [ 91  92  93  94]
 [101 102 103 104]]

[False False False False False  True  True  True  True  True]


In [3]:
partitions = [.8, .1,.1] #.8 train, .1 dev set, .1 test set

train_data, test_data, train_labels, test_labels = train_test_split(fakedata, fakelabels, train_size=partitions[0])

split = partitions[1]/np.sum(partitions[1:])

devset_data, test_data, devset_labels, test_labels = train_test_split(test_data,test_labels,  train_size=split)

In [4]:
print(train_data.shape, test_data.shape)
print(devset_data.shape,devset_labels.shape)
print(test_data.shape,test_labels.shape)

(8, 4) (1, 4)
(1, 4) (1,)
(1, 4) (1,)
